sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- make release
deploy:
  provider: releases
  api_key:
    secure: yPbJcI3juXyzyLYROJgwOdReYtc2ZssthaBRsB0o6d2zAkwcgEySxWek/3Fo/SEgSKDMz1gPctW0j21BBRA7vtQSwXBTySh+G1cn3QraEL88hauyxMeIldpx943jzeUbC9egNCkcEOJhzc/cE/zlZaXQv9Lt88BY7GRQEdKii2N2bILNwQiC1RMtbZ6H8QgqJj3RbSlS+0vgOdk8TtteZZ5+J3k1eFrPUOfLQ8Y1V/ahU6hGgaxxy1gNEhv9JEwSOmzuCBST9YFul4L/AqLhgs6aSc8WO6hNxG1lUvpTqT1CfdmBdsvC9f+vSRYZE+WqqekqgttEsYghknN2b+XOiWAkJi1gh6MgjGPt0sFNNWQzrYIZGAONK1HqYE9YljdR7yDpRyR+sDadqNQCEgnQGI7x8GhE4t+ZceiYa3bKwU/je28LqF8DBTc/tsA94XuC6v21YBblMfWjLSKAzEVDBQYpFQ/9tl1vUfQ8ezbLhWfQHrd+6i2rSQXHdysr3tzjG5CCz4kd+hJuaFiimkgjZYSwOHJ1uvg0wkGO+qUaKsR+Xbgt0DGMxHboUGIgGCzZRnv+DZ0I2dWn3WqKQaQ5HsP9R+RcG96RMqFJXc79Dw41N6c6wehfx4nqACTyKpVFOKkfGPLGGATTB8csUa1z2B8Gp38CqHL7w346gC0I4Xo=
  file: bin/chronos_exporter
  on:
    repo: gettyimages/chronos_exporter
    tags: true
after_deploy:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=gettyimages/chronos_exporter
- docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .
- docker push $REPO:$TRAVIS_TAG
- docker tag $REPO:$TRAVIS_TAG $REPO:latest
- docker push $REPO:latest
env:
  global:
  - secure: NQOwsvKD1QRmL+Z/tDmiJ9E5mk7qJZsT8hgxVeFzQbYDzFwOSO3r9kS9IyyCIinC4JUErvkoCT9Op18jTiJYXjSKL72Q6yW+/W8zaHyRX0oGRhbtyN9Bv85OYvDnGH3qaDAKxbsdc6Ynk0PF9Rwy1g4IHrIe5NhTamY6n9h7yvGRbK4XbDuE6GN05nasVylCe7iPMlyDcRpxPs83V5/5Wj5nSFhWA3yeior4sk4yj3dRfYWJonwKRhpqfGDeUQASb0CfTHG1jk2GrAGX5r2Z8Iepjh0WR5ahJI9EArZh1Zxn5htJIsiuU592AaBSPbLBH6uYeNigeK6si/c3LC/7tXN2/JXGoYKH8BIy8SVhHayocqu7jID9VsE3uJ8f5JKdJhuTLlKVINe/q7BQX9jhxMyMa4QahJjdHnnzLNakC7Y1wnAhbXedJPt78MPhXkOFmyCEvoF04RnAwFT9xw1BMJldZsPAneOLq7cBARg+23BvH2UuceZPb0oqwtC96888N8urcCU7Ri9sDvvaohMjLHRb6jO2EZpfLKIKMkjl3u5HI1ZpDUlVnzpTZnTBSXs0hY+zsBYic/uTw4GmKkjEO98xGtduM5/dLJVJ3SB1qLxAdoM3pOSL0bsniSZvSX95IGYM+uCPA89PEQy6vOCV7wzAtCL8oR0D6VCSNeIgdvM=
  - secure: I7pegWrZz0Rk3y91VQBQtNzqtogjsvkyyvgZmH9FM/e8Y+Hrl7DmOCvNLGiFNiVsPrBvOVoPG/dlZasFeOWd+BKrdqQ6eYuCYRWhPy705zujgC78zkjbhoHGCK1MweKu2Rlh7wghfCTY7MSen/XGModwIFFwMOYPIOGJumNC05yGavC5DjDrJDJJrnyveL9oAOkuOQtMt4t15JYeZDHzz0VV/GvhyvCoM6uN/vdbQ+IvHr/0coEaY23EXMxQ8JO0TF+lNgTHBXsMYAUW4SbusxW7neByg9oeSry87SC2PzSHDO68PYSY0KjuDhERF5A6xSxWP9jBfycwYhmKpTH8cTNL4EgTYGdtkAa2DHzMkMw/7PXaJ83txcpc9m/lSkmA2kUXJnxCf5TNK7khySOREj5AEq830UmbbjbbIs/y0xcuUKgSotxPl9/pAhbWAdWAyzltifHJR33EU8aK2utsE56ZT+cKLuqhC9Udg4Wio2PWZqngwvD/4ISH+RJoPwOgusbjuspx0rH5G5H6fWzNX2t2FLSdnYwx0i8a+8JK7IwgTey+KtJR8rJ2PFkSGzFrED1r21iLJJWAnXl1UQ8r5B4tr0f4tKCpBX2uPuMhEKgHf2lz3Vs/+HrL05NxjrtzcGzy9PfjdHjrROMAfTkRdvV/S+XHYKGCNgUoSoQXZHg=
  - secure: lTyNJojqR9MhGTO4zRZgcNQI1ZDGSC1mwidadKAY1oOGuGouu9GCGVHqLNwMdZfN18rryPgivneP0G0rln2ifpbd+hN7Tfr1dvlB2/5zs2nnEQWdRhddcgbtl2s9xY/BDCzGUmbPn4TumRfywhSKmdyD6qD7zl3QnJlXvnn1QlU5i1EArYJAh+kBZEaxarm7rna7CiM6SGW4f++bXuEZ9vrIJnwX9OhgXxfJwBupEpmaAhNlFodVg0aBeItF2RQFMb2Dn+ZG6Ly+UnK+mpLzLyhECJj28eZ8HvA2cULRt6xkWDEeg/WoUsCvvVRk1QxIYASdw7vuNaJK5YkMOx2eK8ClJxoUTD+dTk+dN93Qx5PB3Q5QyRNL5aIWTtyS89KqugcTPiRP+ksLv3wV181qQy3Fo4Zwfjk/5mc4oa0RgUli8X/P3G2VBkd8Ky3NHrWzqK2PbvkSv5MoOXPsYJtP381NJyNm5oNhyrfPgDdH9nx94TPssGAwXy1WLvume3A2h3OgoK+4Z62lLFl18X8ZA7brQxbMFKXJbWOX3SFK9Q9ORMr2f2Pn7Vu0aEpW95ifT8A5joOw9BHVsP+z/L0zNRfwL/WZNjPAV/+KeGv7yj63j7IFxCwgyXgSs4MPJQ6GYwvVOim3VbJN29OZAnE5NFJTNlcCm3KBt5ttowJApNM=
